[package]
name = "espocrm-rs"
version = "0.1.0"
authors = ["Tobias de Bruijn <github@thedutchmc.nl>"]
edition = "2018"

[dependencies]
serde = "1.0.125"
serde_php = "0.5.0"
reqwest = { version = "0.11.3", features = ["json"]}
rust-crypto = "0.2.36"
base64 = "0.13.0"

