[package]
name = "espocrm-rs"
version = "0.1.0"
authors = ["Tobias de Bruijn <t.debruijn@array21.dev>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/TheDutchMC/espocrm-rs"
description = "A Rust implementation of the EspoCRM PHP API Client"
readme = "README.md"

[dependencies]
serde = "1.0.125"
serde_php = "0.5.0"
reqwest = { version = "0.11.3", features = ["json"]}
rust-crypto = "0.2.36"
base64 = "0.13.0"

